#!/usr/bin/python2.7
import time
import sys
import pytz
from datetime import datetime
from hosted import CONFIG, DEVICE

CONFIG.restart_on_update()

tz = pytz.timezone(CONFIG['timezone'])

while 1:
    time.sleep(60)

    now = pytz.utc.localize(datetime.utcnow(), is_dst=None).astimezone(tz)
    print >>sys.stderr, now

    dow = now.weekday()
    hour = now.hour
    hour = dow * 24 + hour
    print >>sys.stderr, "Hour: %d" % hour
    
    on = CONFIG['times'].get(hour, True)
    print >>sys.stderr, "Screen on: %r" % on

    DEVICE.screen(on = on)
